### ISSUE TITLE
Feature: User can search an event or artist

### ISSUE THREAD

**Issue by cathyygrcia** [cathyygrcia/discover-me#1]
## ⚙️ Feature

User can search an event or artist
## 📐 Functionality

User should be able to search by artist name or genre.  Whenever user refreshes the page, a random selection of events will be displayed.
## 🖼️ Wireframes

![Screen Shot 2023-09-28 at 11 32 28 AM](https://github.com/cathyygrcia/discover-me/assets/90016242/5c272305-01a6-4667-aef3-5d35db6fe89e)
![Screen Shot 2023-09-28 at 11 32 49 AM](https://github.com/cathyygrcia/discover-me/assets/90016242/20746e37-fd08-4bf9-85d9-62a900a03873)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write CSS for mobile devices first.
- [x] Under the header, create the data view for the homepage
- [x] Create search artist / genre buttons
- [x] Complete HTML and CSS so that it matches the figma example
- [x] Create a function getEvents info to send a request to the api for a list of events 
- [x] loop through the data that is retrieved 
- [x] make a DOM tree that creates elements for the image, artist name, event date and venue
- [x] update DOM tree by appending results to the row
- [x] create an array to store different cities we want to display in our random update
- [x] write an expression that generates random events in different cities
- [x] pass the random expression into the getEvents function to update the DOM tree
- [x] Query the DOM for the search buttons and row
- [x] Add an event listener to the search artist button to send a request to the correct end point when a user searches a specific artist
- [x] Clear current values in DOM tree
- [x] Update the DOM tree with the results of the request
- [x] Add event listener to the search genre button to send a request to the correct end point when user searches a specific genre
- [x] Clear current values in DOM tree
- [x] Update the DOM tree with the results of the request
- [x] Test the app by confirming the the correct information is being returned with multiple searches
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors
