### ISSUE TITLE
Feature: User can view artist details

### ISSUE THREAD

**Issue by cathyygrcia** [cathyygrcia/discover-me#2]
## ⚙️ Feature

User can view the details of the artist selected such as an image, genre, instagram, spotify, events, and youtube.

## 🖼️ Wireframes

![Screen Shot 2023-09-28 at 12 28 08 PM](https://github.com/cathyygrcia/discover-me/assets/90016242/7de121fe-3098-48ee-9249-6bf402a912a1)
![Screen Shot 2023-09-28 at 12 28 24 PM](https://github.com/cathyygrcia/discover-me/assets/90016242/236a3cf4-f598-461a-8b50-d7355b5c5a35)

## ✅ Task List

- [x] Update nav bar to include artist info text.
- [x] Add font awesome search icon to nav bar
- [x] Create a new data view for artist info
- [x] Test out content for the new data view in html
- [x] Query for all data views
- [x] Create a view swap function with a single parameter representing the view to show.
- [x] Conditionally check which view was passed as an argument
- [x] Create an addEventListener function to contentRow
- [x] Conditionally check if image icon was clicked
- [x] if image was clicked, call view swap function 
- [x] Make request to API to pull the artists socials and upcoming events
- [x] Create anchor tags to hold response and style them to match figma 
- [ ] Test app
- [ ] Fix all errors
